// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#define GAUSSIANSPLATTING_INVALID_PERSISTENT_HASH						0

#define GAUSSIANSPLATTING_MAX_BVH_NODE_FANOUT_BITS						2
#define GAUSSIANSPLATTING_MAX_BVH_NODE_FANOUT_MASK						((1 << GAUSSIANSPLATTING_MAX_BVH_NODE_FANOUT_BITS)-1)
#define GAUSSIANSPLATTING_MAX_BVH_NODE_FANOUT							(1 << GAUSSIANSPLATTING_MAX_BVH_NODE_FANOUT_BITS)
#define GAUSSIANSPLATTING_BVH_NODE_ENABLE_MASK							((1 << GAUSSIANSPLATTING_MAX_BVH_NODE_FANOUT)-1)

#define GAUSSIANSPLATTING_CUTOFF 3.0f

#define GAUSSIANSPLATTING_MAX_GPU_PAGES_BITS							17
#define GAUSSIANSPLATTING_MAX_GPU_PAGES_MASK							((1 << GAUSSIANSPLATTING_MAX_GPU_PAGES_BITS) - 1)
#define GAUSSIANSPLATTING_MAX_GPU_PAGES								( 1 << GAUSSIANSPLATTING_MAX_GPU_PAGES_BITS)

#define GAUSSIANSPLATTING_INVALID_PERSISTENT_HASH						0

#define GAUSSIANSPLATTING_CLUSTER_MIN_EXPECTED_GPU_SIZE_BITS			9	// Used to determine how many bits to allocate for page cluster count.

//32KB
#define GAUSSIANSPLATTING_ROOT_PAGE_GPU_SIZE_BITS						15
#define GAUSSIANSPLATTING_ROOT_PAGE_GPU_SIZE							(1u << GAUSSIANSPLATTING_ROOT_PAGE_GPU_SIZE_BITS)
#define GAUSSIANSPLATTING_ROOT_PAGE_MAX_CLUSTERS_BITS					(GAUSSIANSPLATTING_ROOT_PAGE_GPU_SIZE_BITS - GAUSSIANSPLATTING_CLUSTER_MIN_EXPECTED_GPU_SIZE_BITS)
#define GAUSSIANSPLATTING_ROOT_PAGE_MAX_CLUSTERS						(1u << GAUSSIANSPLATTING_ROOT_PAGE_MAX_CLUSTERS_BITS)

//128KB
#define GAUSSIANSPLATTING_STREAMING_PAGE_GPU_SIZE_BITS					17
#define GAUSSIANSPLATTING_STREAMING_PAGE_GPU_SIZE						(1u << GAUSSIANSPLATTING_STREAMING_PAGE_GPU_SIZE_BITS)
#define GAUSSIANSPLATTING_STREAMING_PAGE_MAX_CLUSTERS_BITS				(GAUSSIANSPLATTING_STREAMING_PAGE_GPU_SIZE_BITS - GAUSSIANSPLATTING_CLUSTER_MIN_EXPECTED_GPU_SIZE_BITS)
#define GAUSSIANSPLATTING_STREAMING_PAGE_MAX_CLUSTERS					(1u << GAUSSIANSPLATTING_STREAMING_PAGE_MAX_CLUSTERS_BITS)
#define GAUSSIANSPLATTING_ESTIMATED_MAX_PAGE_DISK_SIZE					uint32(GAUSSIANSPLATTING_STREAMING_PAGE_GPU_SIZE * 1.5)

#define GAUSSIANSPLATTING_MAX_NODES_PER_PRIMITIVE_BITS					16
#define GAUSSIANSPLATTING_MAX_RESOURCE_PAGES_BITS						16 // 2GB of 32kb root pages or 4GB of 64kb streaming pages
#define GAUSSIANSPLATTING_MAX_RESOURCE_PAGES_MASK						((1 << GAUSSIANSPLATTING_MAX_RESOURCE_PAGES_BITS) - 1)
#define GAUSSIANSPLATTING_MAX_RESOURCE_PAGES							(1 << GAUSSIANSPLATTING_MAX_RESOURCE_PAGES_BITS)
#define GAUSSIANSPLATTING_MAX_GROUP_PARTS_BITS							5
#define GAUSSIANSPLATTING_MAX_GROUP_PARTS_MASK							((1 << GAUSSIANSPLATTING_MAX_GROUP_PARTS_BITS) - 1)
#define GAUSSIANSPLATTING_MAX_GROUP_PARTS								(1 << GAUSSIANSPLATTING_MAX_GROUP_PARTS_BITS)

#define GAUSSIANSPLATTING_MAX_HIERACHY_CHILDREN_BITS					6
#define GAUSSIANSPLATTING_MAX_HIERACHY_CHILDREN						(1 << GAUSSIANSPLATTING_MAX_HIERACHY_CHILDREN_BITS)

#define GAUSSIANSPLATTING_MAX_CLUSTERS_PER_GROUP_BITS					9
#define GAUSSIANSPLATTING_MAX_CLUSTERS_PER_GROUP_MASK					((1 << GAUSSIANSPLATTING_MAX_CLUSTERS_PER_GROUP_BITS) - 1)
#define GAUSSIANSPLATTING_MAX_CLUSTERS_PER_GROUP						((1 << GAUSSIANSPLATTING_MAX_CLUSTERS_PER_GROUP_BITS) - 1)
#define GAUSSIANSPLATTING_MAX_CLUSTERS_PER_GROUP_TARGET				128
#define GAUSSIANSPLATTING_MAX_CLUSTER_HIERARCHY_DEPTH					14

#define GAUSSIANSPLATTING_MAX_CLUSTERS_PER_PAGE_BITS					(GAUSSIANSPLATTING_STREAMING_PAGE_MAX_CLUSTERS_BITS > GAUSSIANSPLATTING_ROOT_PAGE_MAX_CLUSTERS_BITS ? GAUSSIANSPLATTING_STREAMING_PAGE_MAX_CLUSTERS_BITS : GAUSSIANSPLATTING_ROOT_PAGE_MAX_CLUSTERS_BITS)
#define GAUSSIANSPLATTING_MAX_CLUSTERS_PER_PAGE_MASK					((1 << GAUSSIANSPLATTING_MAX_CLUSTERS_PER_PAGE_BITS) - 1)
#define GAUSSIANSPLATTING_MAX_CLUSTERS_PER_PAGE						( 1 << GAUSSIANSPLATTING_MAX_CLUSTERS_PER_PAGE_BITS)

#define GAUSSIANSPLATTING_TRANSCODE_PASS_INDEPENDENT					0
#define GAUSSIANSPLATTING_TRANSCODE_PASS_PARENT_DEPENDENT				1

#define GAUSSIANSPLATTING_NUM_STREAMING_PRIORITY_CATEGORY_BITS			2
#define GAUSSIANSPLATTING_STREAMING_PRIORITY_CATEGORY_MASK				((1 << GAUSSIANSPLATTING_STREAMING_PRIORITY_CATEGORY_MASK) - 1)
#define GAUSSIANSPLATTING_MAX_PRIORITY_BEFORE_PARENTS					0xFFFFFFE0u